### ISSUE TITLE
Blizzard make my world like invernalia

### ISSUE THREAD

**Issue by set92** [CorgiTaco/Better-Weather#69]
There was a big blizzard and now all the world is full of snow that doesn't melt away. I'm using betterweather 2.0 Beta 4, and this is an image of the situation https://i.imgur.com/QrJfOET.png. I was waiting to see if with time it would melt away but nothing, maybe is something in the configuration or some other mod is not letting the snow melt? Because if the snow is not supposed to melt... the blizzard is a big shitty.

**Comment by set92** [comment]
I think I found it in the settings, file `betterweather-common.toml`.

```
		[Blizzard_Settings.World_Settings.Snow_Decay]
			#Does snow and ice decay after blizzards in biomes within the specified temperature threshold?
			#Recommend disabling this if you have a seasons mod installed!
			#Default: true
			DecaySnowAndIce = false
```

So, I suppose I only have to put this to true.

**Comment by CorgiTaco** [comment]
Blizzards assume the vanilla logic of how snow works(w/ layering and faster placement as the difference). The vanilla logic is... snow does not decay overtime. And the config file you've shown is outdated in the betas. Use the new config for blizzards. 

And snow decay is a complex issue aswell due to the way chunk unloading/loading works and the many variables that exist in regards to that.

If you don't want blizzards altogether... delete the blizzard config.
